---
title: "EDA Presentation"
author: "Thomas, Gedeon, Joann"
date: "2025-06-10"
format: revealjs
---


# EDA Presentation

## Questions

1) Is there a relationship between the number of prenatal visits and if the mother used tobacco, has hypertension or has diabetes?

2) 

## Question 1: Prenatal Visit

```{r}

|# echo = false

library(dplyr)

# cat var Yes = 1, No = 0, Unknown = NA (or 2)
maternal_clean <- maternal %>%
  mutate(
    TobaccoUse_bin = case_when(
      TobaccoUse == "Yes" ~ 1,
      TobaccoUse == "No" ~ 0,
      TobaccoUse == "Unknown" ~ NA_real_
    ),
    Diabetes_bin = case_when(
      PrePregnancyDiabetes == "Yes" ~ 1,
      PrePregnancyDiabetes == "No" ~ 0,
      PrePregnancyDiabetes == "Unknown" ~ NA_real_
    ),
    Hypertension_bin = case_when(
      PrePregnancyHypertension == "Yes" ~ 1,
      PrePregnancyHypertension == "No" ~ 0,
      PrePregnancyHypertension == "Unknown" ~ NA_real_
    )
  )

# remove na in bin col
maternal_cluster <- maternal_clean %>%
  filter(!is.na(TobaccoUse_bin) & !is.na(Diabetes_bin) & !is.na(Hypertension_bin))



library(ggplot2)

# tobacco vs prenatal
ggplot(maternal_cluster, aes(x = factor(TobaccoUse_bin), y = AverageNumberPrenatalVisits)) +
  geom_boxplot() +
  labs(x = "Tobacco Use (0=No, 1=Yes)", y = "Avg. Prenatal Visits")

# diabetes vs prenatal
ggplot(maternal_cluster, aes(x = factor(Diabetes_bin), y = AverageNumberPrenatalVisits)) +
  geom_boxplot() +
  labs(x = "Diabetes (0=No, 1=Yes)", y = "Avg. Prenatal Visits")

# hypertension vs prenatal
ggplot(maternal_cluster, aes(x = factor(Hypertension_bin), y = AverageNumberPrenatalVisits)) +
  geom_boxplot() +
  labs(x = "Hypertension (0=No, 1=Yes)", y = "Avg. Prenatal Visits")

# correlation 
cor.test(maternal_cluster$AverageNumberPrenatalVisits, maternal_cluster$TobaccoUse_bin)
cor.test(maternal_cluster$AverageNumberPrenatalVisits, maternal_cluster$Diabetes_bin)
cor.test(maternal_cluster$AverageNumberPrenatalVisits, maternal_cluster$Hypertension_bin)

```

## Visualization 2

```{r}


```

## Cluster {.scrollable}


```{r}

|# echo = false
  
library(tidyverse)
library(factoextra)
library(ggplot2)
library(ggmosaic)
maternal <- read_csv("https://raw.githubusercontent.com/36-SURE/2025/main/data/maternal.csv")
maternal <- as.tibble(maternal)
maternal[maternal == "Unknown"] <- NA
maternal$PriorBirthsNowDeceased <- as.numeric(maternal$PriorBirthsNowDeceased)
maternal <- maternal %>% 
  drop_na(State, PriorBirthsNowDeceased, 
          TobaccoUse, PrePregnancyDiabetes, 
          PrePregnancyHypertension)
maternal<- maternal %>% 
  mutate(BiTobaccoUse = ifelse(TobaccoUse == "Yes", 1, 0),
         BiPrePregnancyDiabetes = ifelse(PrePregnancyDiabetes == "Yes", 1, 0),
         BiPrePregnancyHypertension = ifelse(PrePregnancyHypertension == "Yes", 1, 0))
num_maternal <- maternal %>% 
  select(PriorBirthsNowDeceased, Births, AveragePrePregnancyBMI, AverageMotherAge,
         AverageBirthWeight, AverageNumberPrenatalVisits, AverageIntervalSinceLastBirth,
         BiPrePregnancyDiabetes,BiPrePregnancyHypertension,BiTobaccoUse)
maternal_pca <- prcomp(num_maternal, center = TRUE, scale. = TRUE)
summary(maternal_pca)
maternal_pc_matrix <- maternal_pca$x
head(maternal_pc_matrix)
maternal_pca$rotation
maternal <- maternal |> 
  mutate(pc1 = maternal_pc_matrix[,1], 
         pc2 = maternal_pc_matrix[,2])
maternal |> 
  ggplot(aes(x = pc1, y = pc2)) +
  geom_point(alpha = 0.5) +
  labs(x = "PC 1", y = "PC 2")
#PCA Biplot
maternal_pca |> 
  fviz_pca_biplot(label = "var",
                  alpha.ind = 0.25,
                  alpha.var = 0.75,
                  labelsize = 5,
                  col.var = "darkblue",
                  repel = TRUE)
#Elbow Plot for PCA
maternal_pca |> 
  fviz_eig(addlabels = TRUE) +
  geom_hline(
    yintercept = 100 * (1 / ncol(maternal_pca$x)), 
    linetype = "dashed", 
    color = "darkred",
  )
#Standardized chosen data & k-means clustered
std_maternal <- num_maternal %>% 
  scale(center = TRUE, scale = TRUE)
kmeans_maternal <- std_maternal |> 
  kmeans(algorithm = "Lloyd", centers = 6, nstart = 30, iter.max = 25) 
prcomp(std_maternal)
#Visualize K-means with PCA
kmeans_maternal |> 
  fviz_cluster(data = std_maternal,
               geom = "point",
               ellipse = FALSE) +
  ggthemes::scale_color_colorblind() + 
  theme_light()
#K-means cluster elbow plot
std_maternal |> 
  fviz_nbclust(kmeans, method = "wss")

```



2nd - tobacco (orthogonal)

hypertension & prior births 


